<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_alertButton</name>
   <tag></tag>
   <elementGuidId>d3ffcc57-8b00-47f8-bee8-3ccbf8af24d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alertButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'alertButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#alertButton</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a1e6ea3c-8123-4b2a-92e4-18e15c733baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alertButton</value>
      <webElementGuid>9864e215-ac86-4dc0-b62a-190c717301ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f5d33957-3d37-418b-8359-263c909d813e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>cc47905d-dcfe-4002-a698-14afb512edb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>alertButton</value>
      <webElementGuid>cba88ed4-d782-4065-bb51-5f3ccbb7e1ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Click me</value>
      <webElementGuid>7e81c912-bd01-4784-91df-f2fc6851100f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8ba1f7755c702c94e23f78d4c394cfe0</value>
      <webElementGuid>976bbcc6-192a-43d5-a5ff-5ccea08c70f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'alertButton']</value>
      <webElementGuid>6344c8ee-d641-4a30-ba58-a31cfd1f7f64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'alertButton']</value>
      <webElementGuid>ae38b216-5cba-4598-9619-359c75a52f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'alertButton' and @type = 'button' and (text() = 'alertButton' or . = 'alertButton')]</value>
      <webElementGuid>f27be4c3-5a9d-4874-b505-96c0063224fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
