<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_promtButton</name>
   <tag></tag>
   <elementGuidId>bc4ab79c-f2ec-4c3a-82e1-720b84a630ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#promtButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'promtButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#promtButton</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>26b44d53-1021-48ca-8216-791a13962d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>promtButton</value>
      <webElementGuid>efd576a5-91d1-47a2-adf3-a3d2fa786634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7d6d1713-a3f0-4179-b58e-5d0e192b280e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>cad2accc-f041-468b-bf41-ee67de6cee6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>promtButton</value>
      <webElementGuid>bd358728-5bdf-4310-a599-1b36b0f6a2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Click me</value>
      <webElementGuid>1892eca9-c156-4636-af5f-f1369cdd746e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f29f8a02786735ad02cbb766e961d83a</value>
      <webElementGuid>e850c93f-8d64-41bc-a50e-f3fe35f08386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'promtButton']</value>
      <webElementGuid>18e20505-0dd3-4f91-9d6f-05f6175ecc91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'promtButton']</value>
      <webElementGuid>30ec6b4d-923c-4f3c-9792-d98a8ce6bda3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'promtButton' and @type = 'button' and (text() = 'promtButton' or . = 'promtButton')]</value>
      <webElementGuid>4d1fc368-8547-4c46-bd27-e9f8cb769a0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
