<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_timerAlertButton</name>
   <tag></tag>
   <elementGuidId>77a9e036-8c4c-43a0-b5b6-0458e2ee0255</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#timerAlertButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'timerAlertButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#timerAlertButton</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>708f9976-c710-40cd-9245-f4d000833830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>timerAlertButton</value>
      <webElementGuid>50a684d4-8a40-49d6-8568-4fb05773122e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5fba9a2e-25d2-4056-8ce1-f1dd6406f588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>5f1e9803-fee6-4b86-b996-ca640b554ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>timerAlertButton</value>
      <webElementGuid>b7dd38e9-fb21-4b69-954e-256ddebc2752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Click me</value>
      <webElementGuid>8e7888ac-e167-440f-8ad1-27bc43220ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d9e5692e684d1cfbe59547ef5067a56e</value>
      <webElementGuid>850ad914-b5de-41a0-bfac-0342e89660c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'timerAlertButton']</value>
      <webElementGuid>f7a65dce-67ac-4e57-9506-1a9204412001</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'timerAlertButton']</value>
      <webElementGuid>039ac4b9-7f1a-422b-924c-da5dc4328839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'timerAlertButton' and @type = 'button' and (text() = 'timerAlertButton' or . = 'timerAlertButton')]</value>
      <webElementGuid>eee55bcc-af26-47c8-9dde-e3966a6626ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
