<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_closeSmallModal</name>
   <tag></tag>
   <elementGuidId>18264af5-98d1-4aaf-81f0-cec4ad26b1bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#closeSmallModal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'closeSmallModal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#closeSmallModal</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>10ba2c41-a78e-4536-bb81-d1bec4c95f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>closeSmallModal</value>
      <webElementGuid>bc4a9e83-39f1-4a75-b325-61c73987fbf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>87132144-ddfe-48b1-80c2-1e4a557e4e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>ba38eca9-92fb-4ebc-832f-05ab59d86f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>closeSmallModal</value>
      <webElementGuid>69f2b265-134c-44f9-84ff-47e72d195cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>4a17de2f-cbd8-486a-bf01-0d60acfbb057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8627728cb7b998681aa141bce5550f74</value>
      <webElementGuid>81a74185-643f-454f-a4d0-e6e0ca04af63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'closeSmallModal']</value>
      <webElementGuid>838ed52d-c797-4096-bb28-c83b2e2c28fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'closeSmallModal']</value>
      <webElementGuid>dae6a6b1-03c9-49ea-ae01-283c842b5e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'closeSmallModal' and @type = 'button' and (text() = 'closeSmallModal' or . = 'closeSmallModal')]</value>
      <webElementGuid>c7b83888-4139-4edb-820a-56807742f85d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
